version: '3.3'
services:
  mysql-forum-db:
    image: 'mysql:8.0.32'
    container_name: mysql-forum-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=forum
      - MYSQL_PASSWORD=root
    ports:
      - '3308:3306'
    volumes:
      - datavolume_forum_mysql:/data/mysql
    networks:
      - forum-network  

  api-forum:
    image: 'bacelarnetto/forum:latest'
    container_name: api-forum
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
    ports:
      - '8089:8080'
    networks:
      - forum-network
    links:
      - mysql-forum-db
      - redis-forum
    depends_on:
      - mysql-forum-db
      - redis-forum

  redis-forum:
    image: 'redis:bullseye'
    container_name: redis-forum
    ports:
      - '6380:6379'
    volumes:
      - datavolume_forum_redis:/var/lib/redis
    networks:
      - forum-network
  
  redis-commander-forum:
    container_name: redis-commander-forum
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis-forum:6379
    ports:
    - "8090:8081"
    networks:
      - forum-network

networks:
  forum-network:
    driver: bridge
volumes:
  datavolume_forum_mysql:
  datavolume_forum_redis: