version: '3.3'
services:
  mysql-forum-db:
    image: 'mysql:latest'
    container_name: mysql-forum-db
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=forum
      - MYSQL_PASSWORD=root
    ports:
      - '3308:3306'
    volumes:
      - datavolume_forum_mysql:/data/mysql
    networks:
      - forum-network  

  api-forum:
    image: 'bacelarnetto/forum:latest'
    container_name: api-forum
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    environment:
      TZ: America/Sao_Paulo
    ports:
      - '8089:8080'
    networks:
      - forum-network
    links:
      - mysql-forum-db
    depends_on:
      - mysql-forum-db
networks:
  forum-network:
    driver: bridge
volumes:
  datavolume_forum_mysql: