###{ POST /login }
POST /login HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "username": "admin@admin.com",
    "password": "admin"
}

###{ POST /topicos }
POST http://localhost:8080/topicos HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjpbeyJpZCI6MSwibm9tZSI6IkxFSVRVUkFfRVNDUklUQSIsImF1dGhvcml0eSI6IkxFSVRVUkFfRVNDUklUQSJ9XSwiZXhwIjoxNjgzMTU1NDkxfQ.ysdDqHfqU2WkjjOcULoCr_bkktd1ESP8mn7oPk53uqGf9QpUVNiFNdw-NDdTXPoIklejuKNtbC6_LuqNlMD3Ew

{
  "titulo": "CACHE do REDIS",
  "mensagem": "Configuração de CACHE do REDIS",
  "idCurso": 2,
  "idAutor":1
}

###{ PUT /topicos }
PUT http://localhost:8080/topicos/1 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjpbeyJpZCI6MSwibm9tZSI6IkxFSVRVUkFfRVNDUklUQSIsImF1dGhvcml0eSI6IkxFSVRVUkFfRVNDUklUQSJ9XSwiZXhwIjoxNjgzMTU1NDkxfQ.ysdDqHfqU2WkjjOcULoCr_bkktd1ESP8mn7oPk53uqGf9QpUVNiFNdw-NDdTXPoIklejuKNtbC6_LuqNlMD3Ew

{
  "titulo": "Duvida Spring Boot 3",
  "mensagem": "Configuração do banco de dados 4"
}

###{ GET /topicos }
GET http://localhost:8080/topicos
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjpbeyJpZCI6MSwibm9tZSI6IkxFSVRVUkFfRVNDUklUQSIsImF1dGhvcml0eSI6IkxFSVRVUkFfRVNDUklUQSJ9XSwiZXhwIjoxNjgzMTU1NjQ0fQ.m_WfNQTEhT3dxLcDi0Pa3YJbzI0X8tx5hQn49vrblWf3oHXas-nL3Wvy3h7wvFfKPQZfp5FPU9Oz4niPo9V6Pg

###{ GET /topicos?nomeCurso=? }
GET http://localhost:8080/topicos?nomeCurso=Kotlin
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjpbeyJpZCI6MSwibm9tZSI6IkxFSVRVUkFfRVNDUklUQSIsImF1dGhvcml0eSI6IkxFSVRVUkFfRVNDUklUQSJ9XSwiZXhwIjoxNjgyNjU3OTU5fQ.RLmskmKiyVvWN9gKu6NJ-YSNr3s93dpjtqENt1ZiIx-xdZFE0gLATVG1H_8JAZA8N-W_N8ArZfxU81USJRmllg

###{ GET /topicos?paginacao }
GET http://localhost:8080/topicos?sort=id,desc&size=2&page=0
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjpbeyJpZCI6MSwibm9tZSI6IkxFSVRVUkFfRVNDUklUQSIsImF1dGhvcml0eSI6IkxFSVRVUkFfRVNDUklUQSJ9XSwiZXhwIjoxNjgzMTU0NDk1fQ.biirJKwIedOwXNryRly7Uf130NaaMIkM9O0d0GCSYpbjKC80uJkwJLrNR5IlEqpZ9VABnRp-XKcUYrIfIbQGgw

###{ GET /topicos/:id }
GET http://localhost:8080/topicos/2 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjpbeyJpZCI6MSwibm9tZSI6IkxFSVRVUkFfRVNDUklUQSIsImF1dGhvcml0eSI6IkxFSVRVUkFfRVNDUklUQSJ9XSwiZXhwIjoxNjgyNjU3OTU5fQ.RLmskmKiyVvWN9gKu6NJ-YSNr3s93dpjtqENt1ZiIx-xdZFE0gLATVG1H_8JAZA8N-W_N8ArZfxU81USJRmllg

###{ GET /topicos/relatorio  }
GET http://localhost:8080/topicos/relatorio HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjpbeyJpZCI6MSwibm9tZSI6IkxFSVRVUkFfRVNDUklUQSIsImF1dGhvcml0eSI6IkxFSVRVUkFfRVNDUklUQSJ9XSwiZXhwIjoxNjgyNjU3OTU5fQ.RLmskmKiyVvWN9gKu6NJ-YSNr3s93dpjtqENt1ZiIx-xdZFE0gLATVG1H_8JAZA8N-W_N8ArZfxU81USJRmllg

###{ DELETE /topicos/:id }
DELETE http://localhost:8080/topicos/2 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkBhZG1pbi5jb20iLCJyb2xlIjpbeyJpZCI6MSwibm9tZSI6IkxFSVRVUkFfRVNDUklUQSIsImF1dGhvcml0eSI6IkxFSVRVUkFfRVNDUklUQSJ9XSwiZXhwIjoxNjgyNjU3OTU5fQ.RLmskmKiyVvWN9gKu6NJ-YSNr3s93dpjtqENt1ZiIx-xdZFE0gLATVG1H_8JAZA8N-W_N8ArZfxU81USJRmllg

###













