###{ POST /topicos }
POST http://localhost:8080/topicos HTTP/1.1
content-type: application/json

{
  "titulo": "CACHE",
  "mensagem": "Configuração de SOCKET",
  "idCurso": 2,
  "idAutor":1
}

###{ PUT /topicos }
PUT http://localhost:8080/topicos/2 HTTP/1.1
content-type: application/json

{
  "titulo": "Duvida Spring Boot 3",
  "mensagem": "Configuração do banco de dados 4"
}

###{ GET /topicos }
GET http://localhost:8080/topicos
Authorization: Basic YWRtaW5AYWRtaW4uY29tOmFkbWlu

###{ GET /topicos?nomeCurso=? }
GET http://localhost:8080/topicos?nomeCurso=Kotlin

###{ GET /topicos?paginacao }
GET http://localhost:8080/topicos?sort=id,desc&size=2&page=0

###{ GET /topicos/:id }
GET http://localhost:8080/topicos/2 HTTP/1.1

###{ GET /topicos/relatorio  }
GET http://localhost:8080/topicos/relatorio HTTP/1.1

###{ DELETE /topicos/:id }
DELETE http://localhost:8080/topicos/2 HTTP/1.1
content-type: application/json

###













